@startuml
start

:Пользователь выбирает аудиофайл;
:Аудиофайл уже загружен и проверен;

label process;
if (Аудиофайл существует в кэше?) then (да)
  :Загрузка аудиофайла из кэша;
else (нет)
  :Обработка аудиофайла;
  :Сохранение аудиофайла в локальное хранилище;
  :Сохранение аудиофайла в кэш;
endif

:Проигрывание аудиофайла в плеере;

while (Воспроизведение активно) is (да)
  if (Пользователь нажал "Пауза") then (да)
    :Приостановка воспроизведения;
    :Ожидание возобновления;
  else (нет)
    if (Пользователь нажал "Стоп") then (да)
      :Остановка воспроизведения;
      :Удаление аудиофайла из локального хранилища;
      goto process;
    endif
  endif
endwhile

:Удаление аудиофайла из локального хранилища;

stop
@enduml
