@startuml
!define C4P https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master
!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!includeurl C4P/C4_Container.puml

Person(user, "Пользователь", "Прослушивает музыку, создает плейлисты, подписывается на артистов, комментирует треки, покупает подписку.")
Person(artist, "Артист", "Загружает музыку, получает статистику, взаимодействует с комментариями.")
Person(advertiser, "Рекламодатель", "Создает рекламные кампании, отслеживает статистику.")
Person(admin, "Администратор", "Управление учетными данными пользователей, контентом, настройками системы, анализ данных сервиса.")

System_Boundary(music_platform, "Платформа стриминга музыки") {
  Container(mobile_app, "Мобильное приложение", "Kotlin", "Мобильное приложение для Android и iOS.")
  Container(web_app, "Веб-приложение", "Kotlin, Spring Boot", "Веб-приложение для пользователей, артистов, рекламодателей и администраторов.")
  Container(api_gateway, "API Gateway", "Kotlin", "")
  System_Boundary(services, "Сервисы") {
    Container(track_service, "Сервис треков", "Kotlin, Spring Boot")
    Container(advertising_service, "Сервис рекламы", "Kotlin, Spring Boot", "", $sprite="kotlin")
    Container(payment_service, "Сервис платежей", "Kotlin, Spring Boot", "", $sprite="kotlin")
    Container(notification_service, "Сервис уведомлений", "Kotlin, Spring Boot", "", $sprite="kotlin")
    Container(support_service, "Сервис техподдержки", "Kotlin, Spring Boot", "", $sprite="kotlin")
    Container(analytics_service, "Сервис аналитики", "Kotlin, Spring Boot", "", $sprite="kotlin")
    Container(authorization_gateway, "Сервис авторизации и аутентификации", "Kotlin, Spring Boot", "", $sprite="kotlin")
  }
  ContainerDb(database1, "База данных треков", "PostgreSQL", "")
  ContainerDb(database2, "База данных рекламы", "PostgreSQL", "")
  ContainerDb(database3, "База данных платежей", "PostgreSQL", "")
  ContainerDb(database4, "База данных уведомлений", "PostgreSQL", "")
  ContainerDb(database5, "База данных техподдержки", "PostgreSQL", "")
  ContainerDb(database6, "База данных аналитики", "PostgreSQL", "")
  ContainerDb(database7, "База данных авторизации и аутентификации", "PostgreSQL", "")
  Container(event_tire, "Брокер сообщений", "Kafka", "")
}

Rel(user, mobile_app, "Использует", "HTTPS")
Rel(user, web_app, "Использует", "HTTPS")
Rel(artist, web_app, "Использует", "HTTPS")
Rel(advertiser, web_app, "Использует", "HTTPS")
Rel(admin, web_app, "Использует", "HTTPS")

Rel(track_service, event_tire, "Создает/читает события")
track_service--[hidden]--> event_tire
Rel(advertising_service, event_tire,  "Создает/читает события")
advertising_service--[hidden]--> event_tire
Rel(payment_service, event_tire, "Создает/читает события")
payment_service--[hidden]--> event_tire
Rel(notification_service, event_tire, "Создает/читает события")
notification_service--[hidden]--> event_tire
Rel(support_service, event_tire, "Создает/читает события")
support_service--[hidden]--> event_tire
Rel(analytics_service, event_tire, "Создает/читает события")
analytics_service--[hidden]--> event_tire
Rel(authorization_gateway, event_tire, "Создает/читает события")
authorization_gateway--[hidden]--> event_tire

Rel(mobile_app, api_gateway, "Запросы на выполнение операций", "HTTPS")
Rel(web_app, api_gateway, "Запросы на выполнение операций", "HTTPS")

Rel(api_gateway, track_service, "Данные о треках", "HTTPS")
Rel(api_gateway, advertising_service, "Данные о рекламе", "HTTPS")
Rel(api_gateway, payment_service, "Управление оплатой", "HTTPS")
Rel(api_gateway, notification_service, "Управление уведомлениями", "HTTPS")
Rel(api_gateway, support_service, "Запросы для техподдержки", "HTTPS")
Rel(api_gateway, analytics_service, "Запросы для аналитики", "HTTPS")
Rel(api_gateway, authorization_gateway, "Авторизация и аутентификация", "HTTPS")

Rel(track_service, database1, "Чтение и запись данных о треках", "HTTPS")
Rel(advertising_service, database2, "Чтение и запись данных о рекламе", "HTTPS")
Rel(payment_service, database3, "Чтение и запись данных о платежах", "HTTPS")
Rel(notification_service, database4, "Чтение и запись данных о уведомлениях", "HTTPS")
Rel(support_service, database5, "Чтение и запись данных для техподдержки", "HTTPS")
Rel(analytics_service, database6, "Чтение и запись данных для аналитики", "HTTPS")
Rel(authorization_gateway, database7, "Чтение и запись данных пользователей", "HTTPS")

System_Ext(paymentSystem, "Платёжная система", "Обработка транзакций и рекуррентных платежей.")
System_Ext(email, "Почтовый шлюз", "Информирование пользователя.")
System_Ext(storage, "Объектное хранилище", "Хранение файлов")
System_Ext(analytics, "Сервис аналитики", "Сбор и анализ метрик для разработчиков.")

Rel(payment_service, paymentSystem, "Производит оплату и поставляет информацию об операциях", "REST API")
payment_service----[hidden]---> paymentSystem
Rel(notification_service, email, "Уведомляет слушателей рассылкой email", "REST API")
notification_service----[hidden]---> email
Rel(track_service, storage, "Хранит и поставляет данные треков", "REST API")
track_service----[hidden]---> storage
Rel(analytics_service, analytics, "Собирает и анализирует данные", "REST API")
analytics_service----[hidden]---> analytics
@enduml